$(function(){
  $('.change').click(function(){
    $(this).text("pushd!!!!");
    alert('['+$(this).val()+']に参加しますか？');
  });
});
$(function(){
  $('.escape').click(function(){
    $(this).text("pushd!!!!");
    alert('['+$(this).val()+']に不参加でよろしいですか？');
  });
});
